"""
Pydantic schemas — the contract between every LangGraph node.

Design notes:
- Every node consumes and produces validated typed objects.
- `confidence` and `evidence` fields are mandatory on assessments — judges and
  candidates both need to see WHY a proficiency was scored a certain way.
- Proficiency is 1-5 (Bloom-aligned), not 1-10. Per Databricks research cited in
  the playbook, low-precision rubrics are dramatically more consistent.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


# ---------------------------------------------------------------------------
# Proficiency scale (Bloom-aligned, 1-5)
# ---------------------------------------------------------------------------

class ProficiencyLevel(int, Enum):
    """
    Bloom's revised taxonomy mapped to a 5-point scale.

    1 = REMEMBER     — recalls facts, definitions, syntax
    2 = UNDERSTAND   — explains concepts, can rephrase
    3 = APPLY        — uses skill in a familiar problem (the hireable bar for juniors)
    4 = ANALYZE      — debugs, compares trade-offs, refactors (mid-level bar)
    5 = EVALUATE/CREATE — designs systems, judges architectural choices (senior bar)
    """
    REMEMBER = 1
    UNDERSTAND = 2
    APPLY = 3
    ANALYZE = 4
    EVALUATE = 5


# ---------------------------------------------------------------------------
# Resume + Job Description (Parser node output)
# ---------------------------------------------------------------------------

class WorkExperience(BaseModel):
    company: str
    role: str
    duration_months: Optional[int] = Field(
        default=None,
        description="Total months in the role. Null if dates are ambiguous.",
    )
    description: Optional[str] = None
    skills_used: list[str] = Field(
        default_factory=list,
        description="Skills explicitly demonstrated or claimed in this role.",
    )


class Project(BaseModel):
    name: str
    description: str
    skills_used: list[str] = Field(default_factory=list)
    url: Optional[str] = None


class Resume(BaseModel):
    """Parsed resume — structured form of the candidate's claimed background."""
    model_config = ConfigDict(extra="ignore")

    name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None

    summary: Optional[str] = None
    skills: list[str] = Field(
        default_factory=list,
        description="All skills extracted from the resume (raw, before ESCO normalization).",
    )
    experience: list[WorkExperience] = Field(default_factory=list)
    projects: list[Project] = Field(default_factory=list)
    education: list[str] = Field(default_factory=list)

    raw_text: Optional[str] = Field(
        default=None,
        description="Original raw text — kept for evidence quoting in the Scorer.",
    )


class JobDescription(BaseModel):
    """Parsed JD — structured form of what the role actually requires."""
    model_config = ConfigDict(extra="ignore")

    title: str
    company: Optional[str] = None
    seniority: Optional[str] = Field(
        default=None,
        description="e.g. 'junior', 'mid', 'senior', 'staff'. Drives scoring thresholds.",
    )

    required_skills: list[str] = Field(
        default_factory=list,
        description="Must-have skills explicitly called out in the JD.",
    )
    preferred_skills: list[str] = Field(
        default_factory=list,
        description="Nice-to-have skills.",
    )
    responsibilities: list[str] = Field(default_factory=list)

    raw_text: Optional[str] = None


# ---------------------------------------------------------------------------
# Interview turns (Interviewer node output)
# ---------------------------------------------------------------------------

class QuestionType(str, Enum):
    CONCEPTUAL = "conceptual"      # "What's the difference between X and Y?"
    APPLIED = "applied"            # "How would you implement X for use case Y?"
    DEBUGGING = "debugging"        # "Here's broken code — what's wrong?"
    DESIGN = "design"              # "Design a system that does X."
    BEHAVIORAL = "behavioral"      # "Tell me about a time you used X."


class InterviewQuestion(BaseModel):
    """A single question generated by the Interviewer for a specific skill."""
    skill: str = Field(description="The skill being probed (ESCO-normalized).")
    question: str
    question_type: QuestionType
    bloom_level: ProficiencyLevel = Field(
        description="Target Bloom level — the IRT 'difficulty' parameter b."
    )
    expected_keywords: list[str] = Field(
        default_factory=list,
        description="Concepts a strong answer would touch on. Used by Scorer as a soft rubric.",
    )


class InterviewTurn(BaseModel):
    """A question + the candidate's response. The unit Scorer evaluates."""
    question: InterviewQuestion
    response: str
    response_timestamp: Optional[str] = None


# ---------------------------------------------------------------------------
# Scorer output — the heart of the assessment
# ---------------------------------------------------------------------------

class SkillAssessment(BaseModel):
    """
    Per-skill proficiency rating with mandatory evidence and confidence.

    Evidence quotes come from BOTH the resume (claims) and the interview (demonstrations).
    Confidence reflects the Scorer's certainty given limited evidence.
    """
    skill: str
    level: ProficiencyLevel
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Scorer's confidence (0-1). Low confidence triggers more questions.",
    )
    evidence: list[str] = Field(
        description="Quoted snippets from resume/interview supporting the rating.",
        min_length=1,
    )
    reasoning: str = Field(
        description="Brief justification — explainable AI for the candidate.",
    )
    gap_to_required: Optional[int] = Field(
        default=None,
        description="JD required level minus actual level. Positive = gap. Null if not required.",
    )


# ---------------------------------------------------------------------------
# Gap analysis + adjacent skills (GapAnalyzer node output)
# ---------------------------------------------------------------------------

class SkillGap(BaseModel):
    """A required skill the candidate lacks or under-demonstrates."""
    skill: str
    required_level: ProficiencyLevel
    current_level: Optional[ProficiencyLevel] = Field(
        default=None,
        description="Null if the candidate has zero demonstrated proficiency.",
    )
    severity: float = Field(
        ge=0.0, le=1.0,
        description="0=trivial gap, 1=critical blocking gap. Drives plan ordering.",
    )
    adjacent_known_skills: list[str] = Field(
        default_factory=list,
        description="Skills the candidate ALREADY has that make this gap learnable.",
    )


class GapAnalysis(BaseModel):
    """Aggregated gap report — input to the PlanGenerator."""
    overall_match_score: float = Field(
        ge=0.0, le=1.0,
        description="Aggregate JD↔candidate fit. Weighted by skill importance.",
    )
    gaps: list[SkillGap]
    strengths: list[str] = Field(
        default_factory=list,
        description="Skills where candidate meets or exceeds JD requirements.",
    )
    summary: str = Field(
        description="One-paragraph honest assessment for the candidate.",
    )


# ---------------------------------------------------------------------------
# Learning plan (PlanGenerator node output)
# ---------------------------------------------------------------------------

class ResourceType(str, Enum):
    VIDEO = "video"
    ARTICLE = "article"
    COURSE = "course"
    DOCS = "docs"
    PROJECT = "project"
    BOOK = "book"


class LearningResource(BaseModel):
    """A single curated resource for acquiring a skill."""
    title: str
    url: str
    resource_type: ResourceType
    source: str = Field(
        description="e.g. 'roadmap.sh', 'YouTube', 'freeCodeCamp', 'DEV.to'",
    )
    estimated_minutes: int = Field(
        description="Rough time investment. Aggregated for the per-skill estimate.",
    )
    reason: str = Field(
        description="Why THIS resource for THIS candidate's gap.",
    )


class LearningModule(BaseModel):
    """One skill-acquisition module within the overall plan."""
    skill: str
    target_level: ProficiencyLevel
    estimated_hours_min: float
    estimated_hours_max: float
    prerequisites: list[str] = Field(
        default_factory=list,
        description="Other skills (in this plan or already known) needed first.",
    )
    resources: list[LearningResource]
    rationale: str


class LearningPlan(BaseModel):
    """The final deliverable — ordered, time-estimated, resource-curated path."""
    candidate_name: Optional[str] = None
    target_role: str
    total_hours_min: float
    total_hours_max: float
    modules: list[LearningModule]
    suggested_order: list[str] = Field(
        description="Skill names in recommended learning sequence.",
    )
    summary: str
