"""
Stage 4 smoke test — real Scorer + GapAnalyzer with mocked LLM calls.

Validates:
- Scorer produces SkillAssessments with mandatory evidence + confidence
- IRT theta is honored (high theta → higher proposed level, low theta → lower)
- gap_to_required is computed correctly (required level - assessed level)
- GapAnalyzer separates strengths from gaps using required_level
- Severity is higher for required-skill gaps than preferred-skill gaps
- adjacent_known_skills populated when sentence-transformers is available
  (gracefully empty if not)
- Summary is generated by the LLM mock

No API keys needed.
"""

import asyncio
import os
import tempfile
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

tmp_db = tempfile.NamedTemporaryFile(suffix=".sqlite", delete=False)
tmp_db.close()
os.environ["SQLITE_CHECKPOINT_PATH"] = tmp_db.name
os.environ.setdefault("OPENAI_API_KEY", "sk-test-not-used")
os.environ["MIN_QUESTIONS_PER_SKILL"] = "1"
os.environ["MAX_QUESTIONS_PER_SKILL"] = "1"  # one question per skill, fastest path through
os.environ["IRT_CONFIDENCE_THRESHOLD"] = "0.0"  # advance immediately after min_questions

from app.models import (
    Resume, JobDescription, WorkExperience,
    InterviewQuestion, QuestionType, ProficiencyLevel,
    SkillAssessment,
)


# ---------------------------------------------------------------------------
# Mocks
# ---------------------------------------------------------------------------

async def fake_parser_node(state):
    return {
        "resume": Resume(
            name="Abhay Sengar",
            skills=["Python", "FastAPI", "LangChain", "Docker", "PostgreSQL"],
            experience=[WorkExperience(
                company="WorkElate", role="AI Engineer Intern",
                duration_months=2,
                description="Built email intent classification with FastAPI and LangChain LCEL.",
                skills_used=["Python", "FastAPI", "LangChain"],
            )],
            raw_text=state["resume_text"],
        ),
        "jd": JobDescription(
            title="Senior AI Engineer",
            seniority="senior",
            required_skills=["Python", "Kubernetes", "LangGraph"],  # 1 strong, 1 unknown, 1 partial
            preferred_skills=["RAG"],
            raw_text=state["jd_text"],
        ),
        "skills_to_assess": ["Python", "Kubernetes", "LangGraph", "RAG"],
        "current_skill_index": 0,
        "interview_turns": [],
        "irt_state": {"theta": {}, "n_questions": {}, "response_history": {}},
        "interview_complete": False,
    }


from pydantic import BaseModel, Field


class FakeResponseScore(BaseModel):
    score: float = Field(ge=0.0, le=1.0)
    keyword_hits: list[str] = []
    strengths: str = "Hit it."
    weaknesses: str = "Could go deeper."
    quote_for_evidence: str = ""


# Pretend the candidate aces Python (theta high), bombs Kubernetes (theta low),
# is mid-tier on LangGraph and RAG.
PER_SKILL_SCORES = {
    "Python": 0.95,
    "Kubernetes": 0.10,
    "LangGraph": 0.55,
    "RAG": 0.55,
}


async def fake_generate_question(skill, bloom_level, resume, jd, asked_questions):
    return InterviewQuestion(
        skill=skill,
        question=f"Mock question for {skill} at level {bloom_level.value}",
        question_type=QuestionType.APPLIED,
        bloom_level=bloom_level,
        expected_keywords=["concept-A", "concept-B"],
    )


async def fake_score_response(question, response):
    return FakeResponseScore(
        score=PER_SKILL_SCORES.get(question.skill, 0.5),
        keyword_hits=["concept-A"],
        strengths="Showed solid grasp.",
        weaknesses="Missed depth on advanced cases.",
        quote_for_evidence=response[:80],
    )


# Mock for the Scorer's per-skill rubric LLM call
from app.graph.nodes import scorer as scorer_mod


async def fake_scorer_completion(*, node, response_model, messages, max_tokens=2048, temperature=0.2):
    """Returns a _SkillRubric or _GapSummary depending on the response_model."""
    # Inspect the user prompt to figure out which skill we're scoring
    user_msg = next((m["content"] for m in messages if m["role"] == "user"), "")

    if response_model.__name__ == "_SkillRubric":
        # Find the skill name (we put it on the first line)
        skill = "Unknown"
        for line in user_msg.splitlines():
            if line.startswith("SKILL TO ASSESS:"):
                skill = line.split(":", 1)[1].strip()
                break
        # Map theta to level: parse theta from the prompt
        theta = 0.0
        for line in user_msg.splitlines():
            if "Converged ability estimate" in line:
                try:
                    theta = float(line.split(":")[1].strip().split()[0])
                except Exception:
                    pass
                break

        # Higher theta → higher proposed level
        if theta >= 1.0:
            level = ProficiencyLevel.ANALYZE
            quality = "HIGH"
        elif theta >= 0.0:
            level = ProficiencyLevel.APPLY
            quality = "MEDIUM"
        elif theta >= -1.0:
            level = ProficiencyLevel.UNDERSTAND
            quality = "MEDIUM"
        else:
            level = ProficiencyLevel.REMEMBER
            quality = "LOW"

        return scorer_mod._SkillRubric(
            skill=skill,
            proposed_level=level,
            evidence_quality=quality,
            resume_evidence=[f"Mock resume quote for {skill}"],
            interview_evidence=[f"Mock interview quote for {skill}"],
            reasoning=f"Mock reasoning for {skill}: theta={theta:+.2f} → level {level.name}.",
        )

    if response_model.__name__ == "_GapSummary":
        from app.graph.nodes.gap_analyzer import _GapSummary
        return _GapSummary(
            summary=(
                "Strong fundamentals in Python with real production experience, "
                "but the Kubernetes gap is the critical blocker for a senior role. "
                "LangGraph and RAG are within reach given existing LangChain knowledge."
            )
        )

    raise RuntimeError(f"Unmocked response_model: {response_model.__name__}")


# ---------------------------------------------------------------------------
# Patch order: parser, question_gen, scorer/gap_analyzer LLM calls
# ---------------------------------------------------------------------------

import app.graph.nodes.parser as parser_mod
parser_mod.parser_node = fake_parser_node

import app.graph.nodes as nodes_pkg
nodes_pkg.parser_node = fake_parser_node

import app.graph.question_gen as qg
qg.generate_question = fake_generate_question
qg.score_response = fake_score_response

# Reload Interviewer so it picks up patched question_gen
import importlib
import app.graph.nodes.interviewer as interviewer_mod
importlib.reload(interviewer_mod)
nodes_pkg.interviewer_node = interviewer_mod.interviewer_node

# Patch the LLM call used by Scorer and GapAnalyzer
import app.graph.nodes.scorer as scorer_mod
scorer_mod.structured_completion = fake_scorer_completion

import app.graph.nodes.gap_analyzer as gap_mod
gap_mod.structured_completion = fake_scorer_completion

# PlanGenerator: stub the node entirely (Stage 4 validates Scorer+Gap, not Plan)
import app.graph.nodes.plan_generator as plan_mod


async def fake_plan_generator_node(state):
    from app.models import LearningPlan, LearningModule, LearningResource, ResourceType
    ga = state.get("gap_analysis")
    modules = []
    if ga and ga.gaps:
        for g in ga.gaps[:2]:
            modules.append(LearningModule(
                skill=g.skill, target_level=g.required_level,
                estimated_hours_min=4.0, estimated_hours_max=8.0, prerequisites=[],
                resources=[LearningResource(
                    title=f"(stub) {g.skill}", url=f"https://roadmap.sh/?q={g.skill}",
                    resource_type=ResourceType.DOCS, source="roadmap.sh",
                    estimated_minutes=240, reason="(stage-4 stub)",
                )], rationale="(stage-4 stub)",
            ))
    return {"learning_plan": LearningPlan(
        candidate_name=state.get("resume", None) and state["resume"].name,
        target_role=state["jd"].title,
        total_hours_min=sum(m.estimated_hours_min for m in modules),
        total_hours_max=sum(m.estimated_hours_max for m in modules),
        modules=modules, suggested_order=[m.skill for m in modules],
        summary="(stage-4 stub)",
    )}


plan_mod.plan_generator_node = fake_plan_generator_node
nodes_pkg.plan_generator_node = fake_plan_generator_node

from app.graph.builder import get_compiled_graph_async, shutdown_graph
from langgraph.types import Command


async def _interrupt_payload(graph, config):
    """Extract interrupt payload from graph state (LangGraph 0.2.60+)."""
    snapshot = await graph.aget_state(config)
    if snapshot and hasattr(snapshot, "tasks") and snapshot.tasks:
        for task in snapshot.tasks:
            if hasattr(task, "interrupts") and task.interrupts:
                first = task.interrupts[0]
                return getattr(first, "value", None) or (first if isinstance(first, dict) else None)
    return None


async def main() -> int:
    print("=" * 70)
    print("STAGE 4 SMOKE TEST — real Scorer + GapAnalyzer")
    print("=" * 70)

    graph = await get_compiled_graph_async()
    print("\n[1] Graph compiled ✓")

    session_id = "smoke-stage4-001"
    config = {"configurable": {"thread_id": session_id}}

    # --- Run through all 4 skills, 1 turn each ---
    print("\n[2] Running through interview (1 turn × 4 skills)...")
    result = await graph.ainvoke({
        "resume_text": "(mock)",
        "jd_text": "(mock)",
        "session_id": session_id,
        "messages": [],
    }, config)

    turn = 0
    answers = {
        "Python": "I built a FastAPI service with async/await for handling 10k concurrent users using uvicorn workers.",
        "Kubernetes": "I have heard of pods.",
        "LangGraph": "I used StateGraph with TypedDict and added conditional edges from a supervisor node.",
        "RAG": "I built a chunking pipeline with semantic splitter and Chroma for retrieval.",
    }
    while True:
        payload = await _interrupt_payload(graph, config)
        if payload is None:
            break
        turn += 1
        skill = payload["skill"]
        ans = answers.get(skill, "I'm not sure.")
        print(f"    Turn {turn}: {skill} (bloom={payload['bloom_level']}) — answering...")
        result = await graph.ainvoke(Command(resume=ans), config)
        if turn > 8:
            raise AssertionError("Loop didn't terminate")

    print(f"    ✓ {turn} turns completed")

    # --- Validate Scorer output ---
    print("\n[3] Validating Scorer output:")
    snapshot = await graph.aget_state(config)
    final = snapshot.values
    assessments: list[SkillAssessment] = final.get("skill_assessments", [])
    assert len(assessments) == 4, f"Expected 4 assessments, got {len(assessments)}"

    by_skill = {a.skill: a for a in assessments}

    py = by_skill["Python"]
    print(f"    ✓ Python:     level={py.level.name:10s} confidence={py.confidence:.2f} "
          f"gap_to_required={py.gap_to_required}")
    assert py.level.value >= ProficiencyLevel.APPLY.value, f"Python level should be ≥APPLY, got {py.level.name}"
    assert len(py.evidence) >= 1, "Evidence list must be non-empty"

    k8s = by_skill["Kubernetes"]
    print(f"    ✓ Kubernetes: level={k8s.level.name:10s} confidence={k8s.confidence:.2f} "
          f"gap_to_required={k8s.gap_to_required}")
    assert k8s.level.value <= ProficiencyLevel.UNDERSTAND.value, "Kubernetes should score low"
    assert k8s.gap_to_required is not None and k8s.gap_to_required > 0, "K8s gap should be positive"

    lg = by_skill["LangGraph"]
    print(f"    ✓ LangGraph:  level={lg.level.name:10s} confidence={lg.confidence:.2f} "
          f"gap_to_required={lg.gap_to_required}")

    rag = by_skill["RAG"]
    print(f"    ✓ RAG:        level={rag.level.name:10s} confidence={rag.confidence:.2f} "
          f"gap_to_required={rag.gap_to_required}")

    # --- Validate GapAnalyzer output ---
    print("\n[4] Validating GapAnalyzer output:")
    gap_analysis = final.get("gap_analysis")
    assert gap_analysis is not None, "GapAnalyzer didn't run"

    print(f"    ✓ overall_match: {gap_analysis.overall_match_score:.2f}")
    print(f"    ✓ strengths:     {gap_analysis.strengths}")
    print(f"    ✓ {len(gap_analysis.gaps)} gap(s) identified:")
    for g in gap_analysis.gaps:
        cur = g.current_level.name if g.current_level else "NONE"
        adj = ", ".join(g.adjacent_known_skills) if g.adjacent_known_skills else "(no adjacency available)"
        print(f"        - {g.skill}: current={cur}, required={g.required_level.name}, "
              f"severity={g.severity:.2f}, adjacent=[{adj}]")

    # Strength check: Python should be in strengths (level ≥ ANALYZE for senior, but our mock
    # caps at ANALYZE only when theta >= 1.0; for a single-question loop with score=0.95,
    # theta hits ~1.5, so this should hold.)
    if py.level.value >= 4:  # ANALYZE = 4 = required for senior
        assert "Python" in gap_analysis.strengths, "Python should be a strength for senior role"
        print("    ✓ Python correctly identified as a strength")
    else:
        print(f"    ⚠ Python at level {py.level.name} — single-question IRT undershot; expected at scale")

    # Kubernetes should be the most severe gap (required + zero proficiency)
    top_gap = gap_analysis.gaps[0]
    assert top_gap.skill == "Kubernetes", f"Top gap should be Kubernetes, got {top_gap.skill}"
    print("    ✓ Kubernetes is correctly the highest-severity gap")

    # RAG is preferred (not required) → severity should be lower
    rag_gap = next((g for g in gap_analysis.gaps if g.skill == "RAG"), None)
    if rag_gap:
        assert rag_gap.severity < top_gap.severity, "Preferred-skill gap should be less severe than required-skill gap"
        print(f"    ✓ RAG (preferred) severity {rag_gap.severity:.2f} < Kubernetes (required) {top_gap.severity:.2f}")

    # Summary should be the LLM-generated string
    assert "Kubernetes" in gap_analysis.summary or "kubernetes" in gap_analysis.summary.lower()
    print(f"    ✓ Summary: {gap_analysis.summary[:100]}...")

    print("\n" + "=" * 70)
    print("✅ STAGE 4 SMOKE TEST PASSED")
    print("=" * 70)

    await shutdown_graph()
    os.unlink(tmp_db.name)
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))